import { useRef, useState, type ChangeEvent } from 'react';
import type { WorkspaceSnapshot, WorkspaceChange } from '../../data/workspace';
import { backupChanges, createWorkspaceBackup, parseWorkspaceBackup, previewBackup, type BackupData, type BackupTable } from '../../domain/backup';

type Props={snapshot:WorkspaceSnapshot;busy?:boolean;demo?:boolean;allowRestore?:boolean;externalError?:string;conflictAction?:()=>void;onImport:(changes:WorkspaceChange[])=>Promise<boolean>};
const tables:[BackupTable,string][]=[['projects','프로젝트'],['tasks','할 일'],['events','일정'],['goals','목표'],['goal_links','목표 연결']];

export default function BackupPanel({snapshot,busy=false,demo=false,allowRestore=true,externalError,conflictAction,onImport}:Props){
  const [candidate,setCandidate]=useState<BackupData|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
  const readGeneration=useRef(0);
  async function readFile(event:ChangeEvent<HTMLInputElement>){const input=event.currentTarget,file=input.files?.[0],generation=++readGeneration.current;setCandidate(null);setError('');setMessage('');if(!file)return;try{if(file.size>5*1024*1024)throw new Error('백업 파일은 5MB 이하만 가져올 수 있습니다.');const parsed=parseWorkspaceBackup(await file.text(),{allowDemo:demo});if(generation===readGeneration.current)setCandidate(parsed)}catch(reason){if(generation===readGeneration.current)setError(reason instanceof Error?reason.message:'백업 파일을 확인할 수 없습니다.')}finally{input.value=''}}
  function download(){const blob=new Blob([JSON.stringify(createWorkspaceBackup(snapshot,demo),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='cloudring-'+(demo?'demo-':'')+'backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage('백업 JSON 다운로드를 요청했습니다. 브라우저 다운로드 목록에서 저장 여부를 확인해 주세요.');}
  async function restore(){if(!candidate||!allowRestore)return;try{const changes=backupChanges(candidate,snapshot);if(!changes.length){setMessage('가져올 항목이 없습니다.');return;}const ok=await onImport(changes);if(ok){setCandidate(null);setError('');setMessage('가져온 항목을 저장했습니다. 기존 항목은 같은 ID에 한해 갱신했습니다.');}}catch(reason){setError(reason instanceof Error?reason.message:'백업 복원 미리보기를 만들지 못했습니다.')}}
  const counts=candidate?previewBackup(candidate,snapshot):null;
  return <section className="dashboard-backup-panel" aria-labelledby="dashboard-backup-title"><h3 id="dashboard-backup-title">{demo?'데모 백업 미리보기':'백업과 복원'}</h3><p>{demo?'아래 파일은 명시적인 샘플 데이터입니다. 실제 계정으로 복원할 수 없습니다.':'프로젝트·할 일·일정·목표·목표 연결을 JSON으로 내보내거나 기존 항목에 병합합니다. 복원은 동일 ID를 갱신하고 새 ID는 추가하며 기존의 다른 항목을 삭제하지 않습니다.'}</p><div className="dashboard-backup-actions"><button type="button" onClick={download} disabled={busy}>JSON 백업 내려받기</button><label>백업 파일 선택<input type="file" accept="application/json,.json" onChange={readFile} disabled={busy}/></label></div>{candidate&&counts&&<div className="dashboard-backup-preview"><strong>{demo?'샘플 파일 미리보기':'복원 미리보기'}</strong><ul>{tables.map(([key,label])=><li key={key}>{label}: {counts[key].incoming}개 · 기존 갱신 {counts[key].existing}개 · 새 항목 {counts[key].new}개</li>)}</ul><p>소유권·로그인 세션·인증 정보는 포함하지 않습니다. 대표 이미지는 경로 메타데이터만 포함하고 이미지 파일은 포함하지 않습니다.</p>{allowRestore&&<button type="button" onClick={()=>void restore()} disabled={busy}>미리보기대로 복원</button>}</div>}{error&&<p role="alert">{error}</p>}{externalError&&<p role="alert">{externalError}</p>}{conflictAction&&<button type="button" onClick={conflictAction}>최신 서버 항목을 반영한 뒤 다시 복원</button>}{message&&<p role="status">{message}</p>}</section>;
}
