import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Plus, Trash2, X } from 'lucide-react';
import { calculateGoalProgress, goalPeriodBounds, validateGoal, validateGoalLinks, type Goal, type GoalLink, type GoalProgressSources, type GoalProgressMode, type GoalPeriodType } from '../../domain/goals';
import { dateLabel } from '../../domain/dates';
import { createUuid } from '../../domain/uuid';

type Props = { goals: Goal[]; setGoals: (goals: Goal[]) => void; links: GoalLink[]; setLinks: (links: GoalLink[]) => void; sources: GoalProgressSources; today: string; projectNames: {id:string;title:string}[]; taskNames: {id:string;title:string}[]; onCommit?:(goal:Goal,links:GoalLink[])=>Promise<boolean>; onDelete?:(goal:Goal)=>Promise<boolean>; externalError?:string; conflictAction?:()=>void; busy?:boolean; currentPeriodLabel?:string; currentPeriodGoals?:Goal[] };
const modes: Record<GoalPeriodType,string> = {day:'일간',week:'주간',month:'월간',quarter:'분기',half_year:'반기',year:'연간',custom:'직접 설정'};
const modeNames: Record<GoalProgressMode,string> = {manual:'직접 입력',target_value:'수치 목표',task_weighted:'연결 항목 가중 평균'};

export default function GoalManager({goals,setGoals,links,setLinks,sources,today,projectNames,taskNames,onCommit,onDelete,externalError,conflictAction,busy=false,currentPeriodLabel='이번 달',currentPeriodGoals=[]}:Props) {
  const [editing,setEditing]=useState<Goal|null>(null), [error,setError]=useState('');
  const [draftLinks,setDraftLinks]=useState<GoalLink[]>([]);
  const dialogRef=useRef<HTMLDivElement>(null), returnFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{if(!editing){const trigger=returnFocus.current;if(trigger)window.setTimeout(()=>{trigger.focus();if(returnFocus.current===trigger)returnFocus.current=null},0);return;}window.setTimeout(()=>dialogRef.current?.querySelector<HTMLElement>('input,select,button')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();closeEditor()}if(e.key==='Tab'&&dialogRef.current){const items=[...dialogRef.current.querySelectorAll<HTMLElement>('button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.hasAttribute('disabled'));if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[editing?.id]);
  const year=today.slice(0,4);
  const annual=goals.filter(g=>g.periodType==='year'&&g.startsOn.startsWith(year));
  const list=[...goals].sort((a,b)=>a.endsOn.localeCompare(b.endsOn));
  const progress=(g:Goal)=>calculateGoalProgress(g.id,{...sources,goals,links});
  function closeEditor(){setEditing(null);setError('')}
  function start(goal?:Goal,event?:HTMLElement){if(!editing)returnFocus.current=event??document.activeElement as HTMLElement;setError('');const next=goal??{id:createUuid(),title:'',periodType:'year' as const,...goalPeriodBounds('year',today),progressMode:'manual' as const,manualProgress:0};setDraftLinks(links.filter(l=>l.goalId===next.id));setEditing(next);}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const d=new FormData(e.currentTarget);const period=d.get('period') as GoalPeriodType;const dates={startsOn:String(d.get('startsOn')),endsOn:String(d.get('endsOn'))};const mode=d.get('progressMode') as GoalProgressMode;const goal:Goal={...editing,title:String(d.get('title')).trim(),periodType:period,...dates,parentGoalId:String(d.get('parent')||'')||null,progressMode:mode,manualProgress:mode==='manual'?Number(d.get('manualProgress')):editing.manualProgress,currentValue:mode==='target_value'?Number(d.get('currentValue')):editing.currentValue,targetValue:mode==='target_value'?Number(d.get('targetValue')):editing.targetValue};
    try{validateGoal(goal,goals.filter(g=>g.id!==goal.id).concat(goal));const nextLinks=mode==='task_weighted'?draftLinks.map(l=>({...l,goalId:goal.id})):[];const nextGoals=goals.some(g=>g.id===goal.id)?goals.map(g=>g.id===goal.id?goal:g):[...goals,goal];const allLinks=[...links.filter(l=>l.goalId!==goal.id),...nextLinks];validateGoalLinks(goal.id,nextLinks,{...sources,goals:nextGoals,links:allLinks});if(onCommit){const ok=await onCommit(goal,nextLinks);if(!ok)return}else{setGoals(nextGoals);setLinks(allLinks)}setEditing(null);}catch(err){setError(err instanceof Error?err.message:'목표 정보를 확인해 주세요.');}}
  function remove(goal:Goal){if(goals.some(g=>g.parentGoalId===goal.id)){setError('하위 목표가 있어 삭제할 수 없습니다.');return false;}setGoals(goals.filter(g=>g.id!==goal.id));setLinks(links.filter(l=>l.goalId!==goal.id&&!(l.targetType==='goal'&&l.targetId===goal.id)));setError('');return true;}
  async function deleteGoal(goal:Goal){if(goals.some(g=>g.parentGoalId===goal.id)){setError('하위 목표가 있어 삭제할 수 없습니다.');return false;}if(onDelete){const ok=await onDelete(goal);if(!ok)return false;}else remove(goal);setEditing(null);return true;}
  const parentOptions=useMemo(()=>goals.filter(g=>g.id!==editing?.id),[goals,editing?.id]);
  return <section className="dashboard-goal-manager" aria-label="목표 관리">
    <article className="dashboard-goal-card"><div className="dashboard-card-heading"><span className="dashboard-icon-box dashboard-icon-blue">◎</span><span className="dashboard-kicker">올해의 목표</span><span className="dashboard-muted">{year}{onCommit?'년 · 개인공간':'년 · 데모'}</span><button className="dashboard-text-button" onClick={e=>start(undefined,e.currentTarget)}>+ 목표</button></div>
      {annual.length?annual.map(g=><div className="dashboard-goal-copy" key={g.id}><div><h2>{g.title}</h2><p>{dateLabel(g.startsOn)} – {dateLabel(g.endsOn)} · {modeNames[g.progressMode]}</p></div><strong>{progress(g)===null?'미설정':`${progress(g)}%`}</strong></div>):<div className="dashboard-goal-copy"><div><h2>연간 목표를 추가해 보세요</h2><p>목표를 저장하면 실제 진행 방식에 맞춰 요약돼요.</p></div><strong>—</strong></div>}
      {annual.slice(0,1).map(g=><div className="dashboard-progress-track" key={g.id}><span style={{width:`${progress(g)??0}%`}}/></div>)}<div className="dashboard-mini-stats"><span><b>{goals.length}</b> 목표</span><span><b>{goals.filter(g=>g.endsOn>=today).length}</b> 진행 중</span><span><b>{annual.length}</b> 연간</span></div>
    </article>
    <article className="dashboard-goal-list-card"><div className="dashboard-card-heading"><span className="dashboard-kicker">현재 기간 목표 · {currentPeriodLabel}</span><button className="dashboard-text-button" onClick={e=>start(undefined,e.currentTarget)}><Plus size={14}/> 추가</button></div><div className="dashboard-goal-list">{currentPeriodGoals.length?currentPeriodGoals.map(g=><div className="dashboard-goal-row" key={`current-${g.id}`}><button className="dashboard-goal-open" onClick={e=>start(g,e.currentTarget)}><b>{g.title}</b><small>{modes[g.periodType]} · {dateLabel(g.endsOn)} 마감</small><span className="dashboard-mini-track"><i style={{width:`${progress(g)??0}%`}}/></span></button><strong>{progress(g)===null?'미설정':`${progress(g)}%`}</strong></div>):<p className="dashboard-form-help">이 기간에 진행 중인 목표가 없어요.</p>}</div><div className="dashboard-card-heading"><span className="dashboard-kicker">전체 목표 목록</span><button className="dashboard-text-button" onClick={e=>start(undefined,e.currentTarget)}><Plus size={14}/> 추가</button></div>{error&&!editing&&<p className="dashboard-goal-error" role="alert">{error}</p>}<div className="dashboard-goal-list">{list.length?list.map(g=><div className="dashboard-goal-row" key={g.id}><button className="dashboard-goal-open" onClick={e=>start(g,e.currentTarget)}><b>{g.title}</b><small>{modes[g.periodType]} · {dateLabel(g.endsOn)} 마감 · {modeNames[g.progressMode]}</small><span className="dashboard-mini-track"><i style={{width:`${progress(g)??0}%`}}/></span></button><strong>{progress(g)===null?'미설정':`${progress(g)}%`}</strong><button className="dashboard-icon-action" aria-label={`${g.title} 삭제`} onClick={()=>void deleteGoal(g)}><Trash2 size={14}/></button></div>):<p className="dashboard-form-help">아직 목표가 없어요. 기간과 진행 방식을 정해 추가할 수 있어요.</p>}</div></article>
    {editing&&<div className="dashboard-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeEditor()}}><div ref={dialogRef} className="dashboard-modal dashboard-goal-modal" role="dialog" aria-modal="true" aria-labelledby="dashboard-goal-title"><div className="dashboard-modal-head"><div><p className="dashboard-eyebrow">{onCommit?'개인 공간 · 목표 관리':'데모 · 목표 관리'}</p><h2 id="dashboard-goal-title">{goals.some(g=>g.id===editing.id)?'목표 수정':'목표 추가'}</h2></div><button className="dashboard-modal-close" onClick={closeEditor} aria-label="닫기"><X size={18}/></button></div>
      <form className="dashboard-form" onSubmit={save}><label>목표 이름<input name="title" required minLength={1} maxLength={200} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} autoFocus/></label><div className="dashboard-form-row"><label>기간<select name="period" value={editing.periodType} onChange={e=>{const periodType=e.target.value as GoalPeriodType;const anchor=goals.some(g=>g.id===editing.id)?editing.startsOn:today;setEditing({...editing,periodType,...goalPeriodBounds(periodType,anchor)})}}>{Object.entries(modes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>상위 목표<select name="parent" value={editing.parentGoalId??''} onChange={e=>setEditing({...editing,parentGoalId:e.target.value||null})}><option value="">없음</option>{parentOptions.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label></div><div className="dashboard-form-row"><label>시작일<input type="date" name="startsOn" value={editing.startsOn} onChange={e=>setEditing({...editing,startsOn:e.target.value})} required/></label><label>종료일<input type="date" name="endsOn" value={editing.endsOn} onChange={e=>setEditing({...editing,endsOn:e.target.value})} required/></label></div><label>진행 방식<select name="progressMode" value={editing.progressMode} onChange={e=>setEditing({...editing,progressMode:e.target.value as GoalProgressMode})}>{Object.entries(modeNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      {editing.progressMode==='manual'&&<label>진행도 <small>0~100%</small><input name="manualProgress" type="number" min="0" max="100" value={editing.manualProgress??0} onChange={e=>setEditing({...editing,manualProgress:Number(e.target.value)})}/></label>}{editing.progressMode==='target_value'&&<div className="dashboard-form-row"><label>현재 값<input name="currentValue" type="number" min="0" step="any" value={editing.currentValue??0} onChange={e=>setEditing({...editing,currentValue:Number(e.target.value)})}/></label><label>목표 값<input name="targetValue" type="number" min="0.01" step="any" value={editing.targetValue??1} onChange={e=>setEditing({...editing,targetValue:Number(e.target.value)})}/></label></div>}
      {editing.progressMode==='task_weighted'&&<fieldset className="dashboard-goal-link-picker"><legend>직접 연결 항목과 가중치</legend>{[...goals.filter(g=>g.id!==editing.id).map(g=>({type:'goal' as const,id:g.id,name:`목표 · ${g.title}`})),...projectNames.map(p=>({type:'project' as const,id:p.id,name:`프로젝트 · ${p.title}`})),...taskNames.map(t=>({type:'task' as const,id:t.id,name:`할 일 · ${t.title}`}))].map(item=>{const checked=draftLinks.some(l=>l.targetType===item.type&&l.targetId===item.id);const current=draftLinks.find(l=>l.targetType===item.type&&l.targetId===item.id);return <label key={`${item.type}:${item.id}`}><input type="checkbox" checked={checked} onChange={e=>setDraftLinks(currentLinks=>e.target.checked?[...currentLinks,{id:createUuid(),goalId:editing.id,targetType:item.type,targetId:item.id,weight:1}]:currentLinks.filter(l=>l.targetType!==item.type||l.targetId!==item.id))}/>{item.name}<input aria-label={`${item.name} 가중치`} type="number" min="0.01" step="any" value={current?.weight??1} onChange={e=>setDraftLinks(currentLinks=>currentLinks.map(l=>l.targetType===item.type&&l.targetId===item.id?{...l,weight:Number(e.target.value)}:l))}/></label>})}</fieldset>}
      {(error||externalError)&&<p className="dashboard-goal-error" role="alert">{error||externalError}{conflictAction&&<button type="button" onClick={conflictAction}>최신 자료를 반영하고 내 입력 다시 저장</button>}</p>}<p className="dashboard-form-help">하위 목표 기간은 상위 목표 안에 포함되어야 하며, 순환과 중복 기여는 저장할 수 없어요.</p><div className="dashboard-form-actions">{goals.some(g=>g.id===editing.id)&&<button type="button" className="dashboard-danger-button" onClick={()=>void deleteGoal(editing)} disabled={busy}>삭제</button>}<button type="button" className="dashboard-secondary" onClick={closeEditor} disabled={busy}>취소</button><button className="dashboard-primary" type="submit" disabled={busy}>{busy?'저장 중…':'저장'}</button></div></form></div></div>}
  </section>;
}
